#!/usr/bin/env bash
# Generated by plan_scg_sets.py -> build the planned SCG-HMM sets.
#
# Each set is independent, so a failure only costs that one set. `--resume`
# is safe to add if a run is interrupted; it refuses if parameters changed.
#
# The -o basename becomes the .hmm filename, so these land as <Taxon>.hmm.
set -euo pipefail

OUT_ROOT="${1:-scg-set-builds}"
mkdir -p "$OUT_ROOT"

# Bacteria (domain) -- 5,148 genomes, selected by domain-set
gtt gen-scg-hmms -w "Bacteria" --derep-rank family --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bacteria"

# Archaea (domain) -- 492 genomes, selected by domain-set
gtt gen-scg-hmms -w "Archaea" --derep-rank family --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Archaea"

# Bacteria-and-Archaea (multi-domain) -- 5,640 genomes, selected by domain-set
gtt gen-scg-hmms -w "Bacteria" -w "Archaea" --derep-rank family --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bacteria-and-Archaea"

# Nanobdellota (phylum) -- 421 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Nanobdellota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Nanobdellota"

# Thermoproteota (phylum) -- 338 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Thermoproteota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Thermoproteota"

# Halobacteriota (phylum) -- 225 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Halobacteriota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Halobacteriota"

# Methanobacteriota (phylum) -- 224 genomes, selected by genomes>=1000+include
gtt gen-scg-hmms -w "Methanobacteriota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Methanobacteriota"

# Thermoplasmatota (phylum) -- 180 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Thermoplasmatota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Thermoplasmatota"

# Micrarchaeota (phylum) -- 93 genomes, selected by genomes>=1000
gtt gen-scg-hmms -w "Micrarchaeota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Micrarchaeota"

# Asgardarchaeota (phylum) -- 90 genomes, selected by include
gtt gen-scg-hmms -w "Asgardarchaeota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Asgardarchaeota"

# Pseudomonadota (phylum) -- 4,932 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Pseudomonadota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Pseudomonadota"

# Patescibacteriota (phylum) -- 3,454 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Patescibacteriota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Patescibacteriota"

# Bacillota (phylum) -- 3,257 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Bacillota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bacillota"

# Bacteroidota (phylum) -- 2,462 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Bacteroidota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bacteroidota"

# Actinomycetota (phylum) -- 1,993 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Actinomycetota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Actinomycetota"

# Planctomycetota (phylum) -- 1,186 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Planctomycetota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Planctomycetota"

# Chloroflexota (phylum) -- 1,062 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Chloroflexota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Chloroflexota"

# Acidobacteriota (phylum) -- 985 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Acidobacteriota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Acidobacteriota"

# Desulfobacterota (phylum) -- 918 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Desulfobacterota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Desulfobacterota"

# Verrucomicrobiota (phylum) -- 694 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Verrucomicrobiota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Verrucomicrobiota"

# Cyanobacteriota (phylum) -- 526 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Cyanobacteriota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Cyanobacteriota"

# Bacillota_I (phylum) -- 513 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Bacillota_I" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bacillota_I"

# Myxococcota_A (phylum) -- 406 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Myxococcota_A" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Myxococcota_A"

# Omnitrophota (phylum) -- 366 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Omnitrophota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Omnitrophota"

# Spirochaetota (phylum) -- 338 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Spirochaetota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Spirochaetota"

# Gemmatimonadota (phylum) -- 267 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Gemmatimonadota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Gemmatimonadota"

# Bdellovibrionota (phylum) -- 245 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Bdellovibrionota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Bdellovibrionota"

# Nitrospirota (phylum) -- 244 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Nitrospirota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Nitrospirota"

# Armatimonadota (phylum) -- 202 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Armatimonadota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Armatimonadota"

# Chlamydiota (phylum) -- 189 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Chlamydiota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Chlamydiota"

# Fusobacteriota (phylum) -- 142 genomes, selected by genomes>=1000+include
gtt gen-scg-hmms -w "Fusobacteriota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Fusobacteriota"

# Myxococcota (phylum) -- 129 genomes, selected by genera>=100
gtt gen-scg-hmms -w "Myxococcota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Myxococcota"

# Campylobacterota (phylum) -- 120 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Campylobacterota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Campylobacterota"

# Thermotogota (phylum) -- 117 genomes, selected by include
gtt gen-scg-hmms -w "Thermotogota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Thermotogota"

# Aquificota (phylum) -- 114 genomes, selected by include
gtt gen-scg-hmms -w "Aquificota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Aquificota"

# Babelota (phylum) -- 112 genomes, selected by genera>=100
gtt gen-scg-hmms -w "Babelota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Babelota"

# Elusimicrobiota (phylum) -- 112 genomes, selected by genera>=100+genomes>=1000
gtt gen-scg-hmms -w "Elusimicrobiota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Elusimicrobiota"

# Zixibacteria (phylum) -- 107 genomes, selected by genera>=100
gtt gen-scg-hmms -w "Zixibacteria" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Zixibacteria"

# Fidelibacterota (phylum) -- 89 genomes, selected by genomes>=1000
gtt gen-scg-hmms -w "Fidelibacterota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Fidelibacterota"

# Synergistota (phylum) -- 62 genomes, selected by include
gtt gen-scg-hmms -w "Synergistota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Synergistota"

# Nitrospinota (phylum) -- 57 genomes, selected by include
gtt gen-scg-hmms -w "Nitrospinota" --target-rank phylum --derep-rank species --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Nitrospinota"

# Deinococcota (phylum) -- 55 genomes, selected by include
gtt gen-scg-hmms -w "Deinococcota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Deinococcota"

# Fibrobacterota (phylum) -- 52 genomes, selected by include
gtt gen-scg-hmms -w "Fibrobacterota" --target-rank phylum --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Fibrobacterota"

# Gammaproteobacteria (class) -- 2,550 genomes, selected by include
gtt gen-scg-hmms -w "Gammaproteobacteria" --target-rank class --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Gammaproteobacteria"

# Alphaproteobacteria (class) -- 2,343 genomes, selected by include
gtt gen-scg-hmms -w "Alphaproteobacteria" --target-rank class --derep-rank genus --min-completeness 90 --max-contamination 5 -j 20 -t 16 -o "$OUT_ROOT/Alphaproteobacteria"
