{% set data = load_file_data("../pyproject.toml", from_recipe_dir=True) %}
{% set py = "3.12" %}

package:
  name: "{{ data.get('project', {}).get('name')|lower }}"
  version: "{{ data.get('project', {}).get('version') }}"

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - python ={{ py }}
    - tar

  run:
    - argcomplete =3.6
    - bc
    - biopython
    - coreutils =9.1
    - curl
    - dendropy =5
    - dos2unix
    - entrez-direct
    - fasttree =2.1.11
    - file
    - gzip
    - hmmer
    - iqtree >=2.2.2
    - kofamscan =1.3.0
    - muscle =5.1
    - pandas
    - parallel
    - prodigal
    - pyarrow =24
    - pyhmmer =0.11.0
    - python ={{ py }}
    - pytest
    - pytest-cov
    - rich
    - rich-argparse
    - requests =2.34
    - sed
    - tqdm =4.68
    - trimal
    - veryfasttree

test:
  commands:
    GToTree -v

about:
  home: https://github.com/AstrobioMike/GToTree/wiki/what-is-gtotree%3F
  license: GPL3
  summary: "GToTree: a user-friendly workflow for phylogenomics"
  dev_url: https://github.com/AstrobioMike/GToTree
  doc_url: https://github.com/AstrobioMike/GToTree/wiki
  description: |
    GToTree is a user-friendly workflow for phylogenomics intended to give more researchers the capability to create phylogenomic trees. The open-access Bioinformatics Journal publication is available here (https://doi.org/10.1093/bioinformatics/btz188), and documentation and examples can be found at the wiki here (https://github.com/AstrobioMike/GToTree/wiki).

    Installation should be performed as:

    ```
    conda create -n gtotree -c astrobiomike -c conda-forge -c bioconda gtotree
    ```
