#!/usr/bin/env bash
# Generated by publish_scg_sets.py -- upload the built SCG-HMM sets.
#
# `--clobber` replaces an asset of the same name, so this is safe to re-run
# after a partial upload. Creating the release is left commented out: making
# a release is the one step worth doing deliberately.
set -euo pipefail

RELEASE_TAG="gtdb-scg-sets-r232"
REPO="AstrobioMike/GToTree"

# gh release create "$RELEASE_TAG" --repo "$REPO" \
#     --title "$RELEASE_TAG" --notes "SCG-HMM sets"

# Acidobacteriota: 97 genes from 985 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Acidobacteriota/Acidobacteriota.hmm" --repo "$REPO" --clobber

# Actinomycetota: 92 genes from 1993 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Actinomycetota/Actinomycetota.hmm" --repo "$REPO" --clobber

# Alphaproteobacteria: 106 genes from 2343 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Alphaproteobacteria/Alphaproteobacteria.hmm" --repo "$REPO" --clobber

# Aquificota: 194 genes from 114 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Aquificota/Aquificota.hmm" --repo "$REPO" --clobber

# Archaea: 51 genes from 492 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Archaea/Archaea.hmm" --repo "$REPO" --clobber

# Armatimonadota: 119 genes from 201 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Armatimonadota/Armatimonadota.hmm" --repo "$REPO" --clobber

# Asgardarchaeota: 87 genes from 90 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Asgardarchaeota/Asgardarchaeota.hmm" --repo "$REPO" --clobber

# Babelota: 108 genes from 112 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Babelota/Babelota.hmm" --repo "$REPO" --clobber

# Bacillota: 79 genes from 3257 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bacillota/Bacillota.hmm" --repo "$REPO" --clobber

# Bacillota_I: 71 genes from 513 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bacillota_I/Bacillota_I.hmm" --repo "$REPO" --clobber

# Bacteria: 52 genes from 5146 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bacteria/Bacteria.hmm" --repo "$REPO" --clobber

# Bacteria-and-Archaea: 30 genes from 5638 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bacteria-and-Archaea/Bacteria-and-Archaea.hmm" --repo "$REPO" --clobber

# Bacteroidota: 118 genes from 2462 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bacteroidota/Bacteroidota.hmm" --repo "$REPO" --clobber

# Bdellovibrionota: 93 genes from 245 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bdellovibrionota/Bdellovibrionota.hmm" --repo "$REPO" --clobber

# Campylobacterota: 182 genes from 120 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Campylobacterota/Campylobacterota.hmm" --repo "$REPO" --clobber

# Chlamydiota: 119 genes from 189 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Chlamydiota/Chlamydiota.hmm" --repo "$REPO" --clobber

# Chloroflexota: 69 genes from 1061 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Chloroflexota/Chloroflexota.hmm" --repo "$REPO" --clobber

# Cyanobacteriota: 119 genes from 525 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Cyanobacteriota/Cyanobacteriota.hmm" --repo "$REPO" --clobber

# Deinococcota: 132 genes from 55 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Deinococcota/Deinococcota.hmm" --repo "$REPO" --clobber

# Desulfobacterota: 101 genes from 918 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Desulfobacterota/Desulfobacterota.hmm" --repo "$REPO" --clobber

# Elusimicrobiota: 107 genes from 112 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Elusimicrobiota/Elusimicrobiota.hmm" --repo "$REPO" --clobber

# Fibrobacterota: 114 genes from 52 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Fibrobacterota/Fibrobacterota.hmm" --repo "$REPO" --clobber

# Fidelibacterota: 116 genes from 89 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Fidelibacterota/Fidelibacterota.hmm" --repo "$REPO" --clobber

# Fusobacteriota: 129 genes from 142 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Fusobacteriota/Fusobacteriota.hmm" --repo "$REPO" --clobber

# Gammaproteobacteria: 108 genes from 2550 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Gammaproteobacteria/Gammaproteobacteria.hmm" --repo "$REPO" --clobber

# Gemmatimonadota: 129 genes from 267 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Gemmatimonadota/Gemmatimonadota.hmm" --repo "$REPO" --clobber

# Halobacteriota: 112 genes from 225 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Halobacteriota/Halobacteriota.hmm" --repo "$REPO" --clobber

# Methanobacteriota: 221 genes from 224 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Methanobacteriota/Methanobacteriota.hmm" --repo "$REPO" --clobber

# Micrarchaeota: 76 genes from 93 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Micrarchaeota/Micrarchaeota.hmm" --repo "$REPO" --clobber

# Myxococcota: 86 genes from 129 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Myxococcota/Myxococcota.hmm" --repo "$REPO" --clobber

# Myxococcota_A: 83 genes from 406 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Myxococcota_A/Myxococcota_A.hmm" --repo "$REPO" --clobber

# Nanobdellota: 53 genes from 421 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Nanobdellota/Nanobdellota.hmm" --repo "$REPO" --clobber

# Nitrospinota: 217 genes from 57 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Nitrospinota/Nitrospinota.hmm" --repo "$REPO" --clobber

# Nitrospirota: 134 genes from 244 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Nitrospirota/Nitrospirota.hmm" --repo "$REPO" --clobber

# Omnitrophota: 130 genes from 366 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Omnitrophota/Omnitrophota.hmm" --repo "$REPO" --clobber

# Patescibacteriota: 53 genes from 3454 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Patescibacteriota/Patescibacteriota.hmm" --repo "$REPO" --clobber

# Planctomycetota: 100 genes from 1186 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Planctomycetota/Planctomycetota.hmm" --repo "$REPO" --clobber

# Pseudomonadota: 97 genes from 4932 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Pseudomonadota/Pseudomonadota.hmm" --repo "$REPO" --clobber

# Spirochaetota: 74 genes from 338 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Spirochaetota/Spirochaetota.hmm" --repo "$REPO" --clobber

# Synergistota: 126 genes from 62 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Synergistota/Synergistota.hmm" --repo "$REPO" --clobber

# Thermoplasmatota: 93 genes from 180 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Thermoplasmatota/Thermoplasmatota.hmm" --repo "$REPO" --clobber

# Thermoproteota: 74 genes from 338 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Thermoproteota/Thermoproteota.hmm" --repo "$REPO" --clobber

# Thermotogota: 161 genes from 117 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Thermotogota/Thermotogota.hmm" --repo "$REPO" --clobber

# Verrucomicrobiota: 95 genes from 694 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Verrucomicrobiota/Verrucomicrobiota.hmm" --repo "$REPO" --clobber

# Zixibacteria: 149 genes from 107 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Zixibacteria/Zixibacteria.hmm" --repo "$REPO" --clobber
