#!/usr/bin/env bash
# Generated by publish_scg_sets.py -- upload the built SCG-HMM sets.
#
# `--clobber` replaces an asset of the same name, so this is safe to re-run
# after a partial upload. Creating the release is left commented out: making
# a release is the one step worth doing deliberately.
set -euo pipefail

RELEASE_TAG="gtdb-scg-sets-r232"
REPO="AstrobioMike/GToTree"

# gh release create "$RELEASE_TAG" --repo "$REPO" \
#     --title "$RELEASE_TAG" --notes "SCG-HMM sets"

# Asgardarchaeota: 87 genes from 90 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Asgardarchaeota/Asgardarchaeota.hmm" --repo "$REPO" --clobber

# Bdellovibrionota: 93 genes from 245 genomes
gh release upload "$RELEASE_TAG" "scg-set-builds/Bdellovibrionota/Bdellovibrionota.hmm" --repo "$REPO" --clobber
