name: testing conda installs

on: workflow_dispatch

jobs:
  install-tests:
    name: ${{ matrix.os }} conda install test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.9"
          channels: astrobiomike,conda-forge,bioconda
          channel-priority: true
          activate-environment: gtotree

      - name: Install GToTree
        shell: bash -el {0}
        run: |
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            arch -x86_64 conda install -y gtotree
          else
            conda install -y gtotree
          fi

      - name: Check GToTree
        shell: bash -l {0}
        run: |
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            arch -x86_64 GToTree -v
          else
            GToTree -v
          fi

